
// Adding floats
f X if X = 0.5 + 1.5.
error "f" if not f 2.0.

// Adding int + floats
g X if X = 0 + 0.5.
h X if X = 0.5 + 0.
error "g" if not g 0.5.
error "h" if not h 0.5.

// Adding string + int
error "string+int" if not "a1" = "a"+1.
error "int+string" if not "2a" = 2+"a".
error "float+string" if not "0.5a" = 0.5+"a".
error "string+float" if not "b0.5" = "b"+0.5.

// Complex chain of things
error "chain" if not "mary123" = "mary" + 1 + 2 + 3.

sdc X if 1<=A<=100 and X = "Hello " + A.
error 123 if not sdc "Hello 10".
