0 has successor 1.
1 has successor 2, predecessor 0.
2 has successor 3, predecessor 1.
3 has predecessor 2.

error "Successor" if A has successor B and not B has predecessor A.
error "Predecessor" if A has predecessor B and not B has successor A.

error "Successor1" if A has successor B and not B has predecessor A and A has successor _ and _ has successor B.
error "Predecessor2" if A has predecessor B and not B has successor A.

red node @1 has edge_to @2.
error "Red node" if not red node @1.
error "Red node" if not red node _.
error "Red" if not red @1.
error "Node" if not node @1.

error "Error 1" if not red node @1 has edge_to @2.
error "Error 2" if red node @1 has edge_to @3.
error "Error 3" if red node @2 has edge_to @2.
error "Error 4" if not red node @1.
error "Error 5" if not @1 has edge_to @2.
error "Error 6" if not red @1 has edge_to @2.
error "Error 6" if not node @1 has edge_to @2.

