// Tests the reordering of projections in the three-variable case.

// Test assertion of facts
1 has successor 2, predecessor 0.
2 has predecessor 1, successor 3.

N has square N*N, successor N+1 if 0 <= N <= 10.

error 5 if not 1 has successor 2, predecessor 0.
error 6 if not 1 has predecessor 0, successor 2.

// Test facts are projected correctly.
error 1 if not 1 has successor 2.
error 2 if not 1 has predecessor 0.
error 3 if not 2 has successor 3.
error 4 if not 2 has predecessor 1.

// Test rules on the left hand side
error 7 if not 10 has square 100.
error 8 if not 10 has successor 11.
error 9 if not 10 has square 100, successor 11.
error 10 if not 10 has successor 11, square 100.

// Test rules on the right hand side

succeeded 1 if 5 has successor 6.
succeeded 2 if 5 has square 25.
succeeded 3 if 5 has successor 6, square 25.
succeeded 4 if 5 has square 25, successor 6.

error 11 if not count S in (succeeded S) = 4.
