// This is the query syntax

person @p1 has name "Fred".
person @p2 has name "Alex", age 30, colour @red.
person @p2 has name "Alex", colour @red, age 30.
person @p2 has name "Alex", colour @green, age 30.

person @p2 has name "Alex", age 30, colour @green.

// This is invalid
// person @p3 has name "Alex", name "Fred".

if
    Person has name Name
then
    query "Query 1" has
    Person Person,
    Name Name.

query "Query 2" has Person Person, Name Name if
    person Person has name Name.

2 is a prime.
query "primes" has prime P if P is a prime.

find query.
