line 9.  // This will permute the results order

// This is the query syntax

person @p1 has name "Fred".
person @p2 has name "Alex", age 30, colour @red.
person @p2 has name "Alex", colour @red, age 30.
person @p2 has name "Alex", colour @green, age 30.

person @p2 has name "Alex", age 30, colour @green.

// This is invalid
// person @p3 has name "Alex", name "Fred".

person "Joe" has name "Bloggs".

if
    person Person has name Name
then
    query "Query 1" has
    Person Person,
    Name Name.

query "Query 2" has Person Person, Name Name if
    person Person has name Name.

2 is a prime.
query "primes" has prime P if P is a prime.
query "Unused parameter" has entity E, name N, line 20, file "C:\\foo.c" if
    E=@f1 and N = "function1" or
    E=@f2 and N = "function2" or
    E=@f3 and N = "main".

// query "Unused parameter" has entity E, name N if 1=1.
