large mouse "Mickey".
small mouse "Mini".
large dog "Pluto".

yellow house X if mouse X.

horse X if large mouse X.

expected_large "Mickey".
expected_large "Pluto".
expected_mouse "Mickey".
expected_mouse "Mini".
expected_yellow "Mickey".
expected_yellow "Mini".
expected_horse "Mickey".

error X if 
    large X and not expected_large X
    or
    expected_large X and not large X.

error X if 
    mouse X and not expected_mouse X
    or
    expected_mouse X and not mouse X.

error X if 
    yellow X and not expected_yellow X
    or
    expected_yellow X and not yellow X.

error X if 
    horse X and not expected_horse X
    or
    expected_horse X and not horse X.
