// A tour of Logical syntax.

// These are facts - unary relations
print "These are unary predicates".
person "Fred".
person @.
person 123.
person @123.
person @person-123.
person 3.14.
person true.
person false.

print "".
print "Here are the people:".
print "".

// You can define global constants as follows.
pi 3.14159.
3.1415926 is pi.
googol 1.0e100.
googol 1e100.
username "calum".

// You can define multiple facts in the same statement.
large fish 1234.

// These are the equivalent:
large fish @f1 and small fish @f2.
fish @f1 is large and fish @f2 is small.

// In Datalog:
fish(@f1).
large(@f1).
fish(@f2).
small(@f2).

// Binary relations are defined using `has` and `,`.

// These are equivalent. They define a unary relation `circle` and the binary `radius`
circle @c1, radius 10.
circle @c2 has radius 20.
print "....".


// These are equivalent. `a` and `an` are optional and can be used to aid readability.
@fred has first_name "Fred".
@fred has a first_name "Fred".
@fred has an first_name "Fred".
@fred, first_name "Fred".
@fred has first_name "Fred", surname "Brooks", age 99.

// Ternary or more relations
person @fred has a child "Bill", position 0, age 10.
@fred has a child "Mary", position 1, age 8.

// Same as:
child_position_age(@fred, "Mary", 1, 8).

// Rules
circle C has diameter D if C has radius R and D = R*3.14159.
circle C has diameter D if C has radius R and pi Pi and D = R*Pi.
circle C has diameter D if C has radius R and Pi is pi and D = R*Pi.

X has ancestor Y if 
    X has parent Y or 
    X has parent Z and Z has ancestor Y.

X has parent Y if X has mother Y or X has father Y.

P is retired if P has age A and A>=65.

P is retired if
    P has age A and (P is male and A>=65 or P is female and A>=60).

P is retired if 
    P has age A and (P is male and A>=65 or not male P and A>=60).

P is retired if 
    P has age A and (P is male and A>=65 or P is not male and A>=60).

P is retired if 
    P has age A and (P is male and A>=65 or P is not a male and A>=60).

P is orphan if P has no parent.
P is orphan if P has no parent _.

// This defines the relation `retired`, not the relation `person`.
person P is retired if 
    P has age A and (P is male and A>=65 or P is female and A>=60).

person X is old if X has age A and A>=80.
person X is young if not X is old.



// Quantifiers

1 has cash 2.
2 has value 3.
person X has money M if M = sum V over C in (X has cash C and C has value V).
person X has money sum V over C in (X has cash C and C has amount V).
person X has coins count C in (X has cash C).
person X is rich if sum V over C in (X has cash C and C has value V) > 100.

person X is rich if 
    all (rich X) in X has parent P and rich P.

// This states two facts: rich P and person P.
rich person @p1.

// This defines two predicates: person/1 and rich/1
person X and rich X if foo X.
person X and rich X, money M if foo X and M=1000.

rich person X, money M if foo X and M=1000.
rich person X has money M if foo X and M=1000.
rich person X has money 1000 if foo X.
money(X,M) :- rich(X), person(X), foo(X), eq(M,1000).


// rich person @p2 has name "Frank".
person P is orphan if not P has parent. 

// Datalog syntax:

f().
f() :- g().
f() :- g(), h().
f(x) :- g(x), h(x).
f(x) :- g(x), h(_).
f() :- g(); h(); i().
f() :- not g().
f() :- (g()).
f() :- (g();h()), i().

// Datalog query:

?- f(X).

// `print` is a predicate with a side-effect.

// `delete` is a special predicate.
// It deletes all statements and rules.
delete person X.
delete person.
delete person X has surname S.
delete _.

delete person P if P has surname "Smith".

evaluation-step-limit 251.
expected-results 40.
expected-errors 0.

// Queries
find person.

1 has radius 2, diameter 3.
find person P.
find person.
find circle C, radius R.
find C has radius R.
find C has radius R, diameter D.
find C has radius R, diameter D if D>10.
find circle C and person P.
find circle C and person P if 
    P has age A and C has diameter A.
find circle C and person P, surname S if 
    P has age A and C has diameter A.

// Query using a variable list
find P in person P.
find P, S in person P, surname S.

print "Syntax test passed".
