
testcase "test1.csv" has contents "1, 2, 3".
testcase "test2.csv" has contents "12,13,14\n15,16,17\n".
testcase "test3.csv" has contents "ab,, ,a,".
testcase "test4.csv" has contents ",".
testcase "test5.csv" has contents "".
testcase "test6.csv" has contents "\n".

if
    testcase F has contents C
then
    file F has contents C.

if
    testcase F
then
    csv:read F.

?- csv:file:row:col:text(_,_,_,_).

find csv:file _ has row _, col _, text _.