mixed 1.
mixed true.
mixed 3.14.
mixed "abc".

m has type "string" if mixed m and is-string m.
m has type "int" if mixed m and is-int m.

error "Strings" if not is-string "sdc".
error "Strings 2" if is-string 123.
error "Strings 3" if not (mixed m and is-string m).
error "Strings 4" if 1 != find count m in (mixed m and is-string m).
error "Strings 5" if not "abc" has type "string".

assert-string "abc".
assert-int 123.
assert-bool true.
assert-float 3.14.
assert-at-string @123.

error "bool 1" if not is-bool true.
error "bool 2" if is-bool 1.
error "bool 2" if is-bool x.