0 has succ 1.
1 has succ 2, pred 0.
2 has succ 3, pred 1.
3 has succ 4, pred 2.

print "Expect 4 results:".
std:query X has Successor Y if X has succ Y.

X has succ2 Y if X has succ Z and Z has succ Y.

print "Expect 3 results:".
std:query X has Successor2 Y if X has succ2 Y.

test X if _ has succ2 X.
test2 X if X has succ2 _.

// Test the basic binding 

error "Failed BB" if not 1 has succ 2.
error "Failed BF" if not 1 has succ _.
error "Failed FB" if not _ has succ 1.
error "Failed FF" if not _ has succ _.

error "Failed succ2" if not 1 has succ2 3.

print "Expect 3 results:".
std:query X if test X.

print "Expect 3 results:".
std:query X if test2 X.

expected-results 13.

