expected-results 2.

error "uc1" if not string "abc" has uppercase "ABC".
error "lc1" if not string "ABC" has lowercase "abc".

error "uc2" if not string "abc" has uppercase x and x="ABC".
error "lc2" if not string "ABC" has lowercase x and x="abc".

std:query "String1" has Lowercase l if
    string "ABCabc123" has lowercase l.

if string "ABCabc123" has uppercase u
then std:query "String2" has Uppercase u.