load-module parsers.
import report-summary.

parsers:parse "AllInOne8.java".

error e if parsers:file _ has errormessage e.
error "Failed to register file" if not parsers:file _.

parsers:node n has children c if n is a parsers:node and c = count child in (parsers:node child has parent n).

nodetype t has Count c if 
    parsers:node _ has type t and 
    c = count m in (parsers:node m has type t).

expected-results 117.

error "Statements" if not count s in (java:statement s)=19.
