print "Imported module report-summary!".

query "Lines of code" has result 1.

parsers:number-of-files n if n = count f in (parsers:file f).

java:statement s if parsers:node s has type "statement".

parsers:file _.
parsers:node _ has type _.  // Declaration

t is a nodetype if parsers:node _ has type t.

query "Number of files" has result n if n is parsers:number-of-files.

query "Node types" has nodetype t, nodecount c if
    t is a nodetype and 
    c = count m in (parsers:node m has type t).


