print "Imported module report-summary!".

query "Lines of code" has result 1.

parsers:number-of-files n if n = find count f in (parsers:file f).

java:statement s if parsers:node s has type "statement".

parsers:file _.
parsers:node _ has type _.  // Declaration

t is a nodetype if parsers:node _ has type t.

query "Number of files" has result n if n is parsers:number-of-files.

query "Node types" has nodetype t, nodecount c if
    t is a nodetype and 
    c = find count m in (parsers:node m has type t).

root m if parsers:node m has parent p and not parsers:node p.
leaf m if parsers:node m and not parsers:node c has parent m.

// query "Root node" has node n if root n.

if 
    parsers:node Node and
    N = find count Child in (parsers:node Child has parent Node)
then
    node Node has children N.

enable_leaves _.

// enable_leaves 1.

query "Leaf node" has node n, type Type, text t, children c if 
    enable_leaves _ and
    leaf n and parsers:token n has text t and parsers:node n has type Type and
    node n has children c.
